# Auto trigger when changes on main
trigger:
  branches:
    include:
      - main

# Use the Microsoft hosted runners
pool:
    vmImage: 'ubuntu-latest'

# Load the pipeline template repo
resources:
  repositories:
  - repository: az-aib-pipeline-template
    type: github
    endpoint: Azure
    name: kevinpz/az-aib-pipeline-template



steps:
- checkout: self
- checkout: az-aib-pipeline-template

# Run the build pipeline
extends:
  template: build-image.yml@az-aib-pipeline-template
  parameters:
    src_image_publisher: Canonical
    src_image_offer: 0001-com-ubuntu-server-focal
    src_image_sku: 20_04-lts-gen2
    image_name: ubuntu2004lts